### ISSUE TITLE
include cell and channels

### ISSUE THREAD

**Issue by andrisecker** [OpenSourceBrain/OpenCortex#8]
Hi,

I tried to include a cell model from a different subdir. (with channels from an other different subdir.) and have an issue with that... _I have 3 diff folders within NeuroML2 (cells, channels, network)_

Calling: `oc.include_neuroml2_cell()`
includes the files with a modified path: `new_file = '%s/%s' % (nml_doc.id, os.path.basename(cell_nml2_path))` (see: https://github.com/OpenSourceBrain/OpenCortex/blob/master/opencortex/build/__init__.py#L1926) which is fine with most of the settings!

But calling `oc.generate_lems_simulation()` tries to include ../channels/*.channel.nml (as specified in the cell models) but after opencortex creates a subfolder (called nml_doc.id) with dumped cells and channels it will throw an error: can't find ../channels/... (since the file organization structure is the same)

I tried to use: `oc.save_network(nml_doc, nml_fName, validate=True, format="xml", use_subfolder=False)` which doesn't copy the files to the folder, but still uses path as nml_doc.id/*.nml in nml includes, and doesn't even pass the validation!

Any ideas to solve?

**Comment by pgleeson** [comment]
Can you try directly adding the include for the cell file to the nml_doc:

    nml_doc.includes.append(neuroml.IncludeType(cell_file))

Then OC doesn't know anything about it, it should save the network file as normal, and as long as the relative paths are correct it should pass validation.

**Comment by andrisecker** [comment]
Thanks, that helped!
(Then oc_build.cell_ids_vs_nml_docs[] doesn't get updated, so I also had to do:
`oc_build.cell_ids_vs_nml_docs["<cell_name>"] = pynml.read_neuroml2_file("../cells/<cell_name>.cell.nml", include_includes=False)`)

**Comment by andrisecker** [comment]
I think you can close this one!
